heat_template_version: 2015-04-30

description: "TSE PE Demo Stack"

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    constraints:
      - { custom_constraint: nova.keypair }
  pe_demo_build_url:
    type: string
    description: URL to download pe-demo build tarball from
    default: http://tse-builds.s3-us-west-2.amazonaws.com/2017.2.x/releases/pe-demo-latest.tar.gz
  pe_source_url:
    type: string
    description: URL to download Puppet Enterprise from (tar.gz or tar)
    default: http://pe-releases.puppetlabs.net/2017.2.1/puppet-enterprise-2017.2.1-el-7-x86_64.tar.gz

resources:

  master_server:
    type: OS::Nova::Server
    properties:
      name: "master.inf.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "m1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            set -ex
            hostname $(curl http://169.254.169.254/latest/meta-data/local-hostname)
            echo $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) $(hostname) >> /etc/hosts
            echo $gitlab_floating_ip gitlab.inf.puppet.vm >> /etc/hosts
            mkdir -p /etc/puppetlabs/puppet
            echo '*' > /etc/puppetlabs/puppet/autosign.conf
            retrycurl() { set +e; while :; do curl "$@"; [ "$?" = 0 ] && break; done; set -e; }
            retrycurl --max-time 30 -o pe.archive $pe_source_url
            retrycurl --max-time 15 -o pe-demo.tar.gz $pe_demo_build_url
            tar -xf pe.archive
            mkdir pe-demo && tar -xzf pe-demo.tar.gz -C pe-demo --strip-components 1
            cat > pe.conf <<-EOF
            {
              "console_admin_password": "puppetlabs"
              "puppet_enterprise::puppet_master_host": "%{::trusted.certname}"
              "puppet_enterprise::use_application_services": true
              "puppet_enterprise::profile::master::r10k_remote": "/opt/puppetlabs/repos/control-repo.git"
              "puppet_enterprise::profile::master::r10k_private_key": ""
              "puppet_enterprise::profile::master::code_manager_auto_configure": true
              "puppet_enterprise::profile::master::check_for_updates": false
            }
            EOF
            ./puppet-enterprise-*-el-7-x86_64/puppet-enterprise-installer -c pe.conf
            ./pe-demo/scripts/provisioners/puppet_master_bootstrap.sh
          params:
            $gitlab_floating_ip: { get_attr: [gitlab_floating_ip, ip] }
            $pe_demo_build_url: { get_param: pe_demo_build_url }
            $pe_source_url: { get_param: pe_source_url }

  master_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  master_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: master_floating_ip }
      server_id: { get_resource: master_server }

  gitlab_server:
    type: OS::Nova::Server
    properties:
      name: "gitlab.inf.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "m1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data: &linux_agent_user_data
        str_replace:
          template: |
            #!/bin/bash
            echo $master_ip master.inf.puppet.vm >> /etc/hosts
            hostname $(curl http://169.254.169.254/latest/meta-data/local-hostname)
            echo $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) $(hostname) >> /etc/hosts
            while :; do
              if curl -f -s --head http://master.inf.puppet.vm:81/deployed.txt; then
                break
              else
                sleep 10
              fi
            done
            curl -k https://master.inf.puppet.vm:8140/packages/current/install.bash | bash
          params:
            $master_ip: { get_attr: [master_server, first_address] }

  gitlab_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  gitlab_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: gitlab_floating_ip }
      server_id: { get_resource: gitlab_server }

  centos7a_server:
    type: OS::Nova::Server
    properties:
      name: "centos7a.pdx.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  centos7a_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  centos7a_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: centos7a_floating_ip }
      server_id: { get_resource: centos7a_server }

  centos7b_server:
    type: OS::Nova::Server
    properties:
      name: "centos7b.syd.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  centos7b_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  centos7b_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: centos7b_floating_ip }
      server_id: { get_resource: centos7b_server }

  centos6a_server:
    type: OS::Nova::Server
    properties:
      name: "centos6a.pdx.puppet.vm"
      image: "6ed7eb41-ae01-4f7f-8294-36e86e045bb6"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  centos6a_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  centos6a_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: centos6a_floating_ip }
      server_id: { get_resource: centos6a_server }

  centos6b_server:
    type: OS::Nova::Server
    properties:
      name: "centos6b.syd.puppet.vm"
      image: "6ed7eb41-ae01-4f7f-8294-36e86e045bb6"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  centos6b_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  centos6b_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: centos6b_floating_ip }
      server_id: { get_resource: centos6b_server }

  ubuntu1404a_server:
    type: OS::Nova::Server
    properties:
      name: "ubuntu1404a.pdx.puppet.vm"
      image: "ubuntu_14.04_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  ubuntu1404a_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  ubuntu1404a_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: ubuntu1404a_floating_ip }
      server_id: { get_resource: ubuntu1404a_server }

  ubuntu1404b_server:
    type: OS::Nova::Server
    properties:
      name: "ubuntu1404b.syd.puppet.vm"
      image: "ubuntu_14.04_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  ubuntu1404b_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  ubuntu1404b_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: ubuntu1404b_floating_ip }
      server_id: { get_resource: ubuntu1404b_server }

  rgbankdev_server:
    type: OS::Nova::Server
    properties:
      name: "rgbank-dev.pdx.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  rgbankdev_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  rgbankdev_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: rgbankdev_floating_ip }
      server_id: { get_resource: rgbankdev_server }

  rgbankappserver01_server:
    type: OS::Nova::Server
    properties:
      name: "rgbank-appserver-01.pdx.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  rgbankappserver01_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  rgbankappserver01_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: rgbankappserver01_floating_ip }
      server_id: { get_resource: rgbankappserver01_server }

  rgbankappserver02_server:
    type: OS::Nova::Server
    properties:
      name: "rgbank-appserver-02.pdx.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  rgbankappserver02_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  rgbankappserver02_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: rgbankappserver02_floating_ip }
      server_id: { get_resource: rgbankappserver02_server }

  rgbankdatabase01_server:
    type: OS::Nova::Server
    properties:
      name: "rgbank-database-01.pdx.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  rgbankdatabase01_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  rgbankdatabase01_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: rgbankdatabase01_floating_ip }
      server_id: { get_resource: rgbankdatabase01_server }

  rgbankloadbalancer01_server:
    type: OS::Nova::Server
    properties:
      name: "rgbank-loadbalancer-01.pdx.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  rgbankloadbalancer01_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  rgbankloadbalancer01_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: rgbankloadbalancer01_floating_ip }
      server_id: { get_resource: rgbankloadbalancer01_server }

  server2012r2a_server:
    type: OS::Nova::Server
    properties:
      name: "server2012r2a.pdx.puppet.vm"
      image: "windows_2012_r2_std_eval_x86_64"
      flavor: "g1.large"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data: &windows_agent_user_data
        str_replace:
          template: |
            #ps1_sysnative

            $puppet_server = "master.inf.puppet.vm"
            $agent_certname = Invoke-RestMethod -Uri http://169.254.169.254/latest/meta-data/local-hostname

            #Adding a host entry for the PE server
            $host_entry = "$master_ip $puppet_server"
            $host_entry | Out-File -FilePath C:\Windows\System32\Drivers\etc\hosts -Append -Encoding ascii

            $master_uri = "http://${puppet_server}:81/deployed.txt"

            #Wait for the master to be available before installing the agent
            :loop while ($true) {
              $request = [System.Net.WebRequest]::Create($master_uri)
              $response = $request.GetResponse()
              switch ($response.StatusCode.value__)
              {
                200
                {
                  #PUT A SPACE BETWEEN '{' and '$', OR THEY WILL TURN INTO '%'
                  [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
                  $webClient = New-Object System.Net.WebClient
                  $webClient.DownloadFile("https://${puppet_server}:8140/packages/current/install.ps1", 'install.ps1')
                  .\install.ps1 "main:certname=${agent_certname}"
                  Write-Host "Installation has completed."
                  break loop
                }
                default { Write-Host "Waiting for the installer to be available"; sleep 30 }
              }
            }
          params:
            $master_ip: { get_attr: [master_server, first_address] }

  server2012r2a_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  server2012r2a_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: server2012r2a_floating_ip }
      server_id: { get_resource: server2012r2a_server }

  server2012r2b_server:
    type: OS::Nova::Server
    properties:
      name: "server2012r2b.syd.puppet.vm"
      image: "windows_2012_r2_std_eval_x86_64"
      flavor: "g1.large"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *windows_agent_user_data

  server2012r2b_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  server2012r2b_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: server2012r2b_floating_ip }
      server_id: { get_resource: server2012r2b_server }

outputs:
  master_ip:
    description: The IP address of the Puppet master server
    value: { get_attr: [master_floating_ip, ip] }
  gitlab_ip:
    description: The IP address of the Gitlab server
    value: { get_attr: [gitlab_floating_ip, ip] }
