heat_template_version: 2015-04-30

description: "TSE PE Demo Stack - centos7 machines"

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    constraints:
      - { custom_constraint: nova.keypair }
  pe_demo_build_url:
    type: string
    description: URL to download pe-demo build tarball from
    default: http://tse-builds.s3-us-west-2.amazonaws.com/2017.2.x/releases/pe-demo-latest.tar.gz
  pe_source_url:
    type: string
    description: URL to download Puppet Enterprise from (tar.gz or tar)
    default: http://pe-releases.puppetlabs.net/2017.2.1/puppet-enterprise-2017.2.1-el-7-x86_64.tar.gz

resources:

  centos7a_server:
    type: OS::Nova::Server
    properties:
      name: "centos7a.pdx.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  centos7a_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  centos7a_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: centos7a_floating_ip }
      server_id: { get_resource: centos7a_server }

  centos7b_server:
    type: OS::Nova::Server
    properties:
      name: "centos7b.syd.puppet.vm"
      image: "centos_7_x86_64"
      flavor: "g1.medium"
      key_name: { get_param: key_name }
      security_groups:
        - "sg0"
      user_data:
        <<: *linux_agent_user_data

  centos7b_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: "ext-net-pdx1-opdx1"

  centos7b_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: centos7b_floating_ip }
      server_id: { get_resource: centos7b_server }
